# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Vox
version:      1.1
version_from: lib/WWW/Vox.pm
installdirs:  site
requires:
    Image::Info:                   1
    JSON::Any:                     1
    Test::MockObject:              0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
