--- #YAML:1.0
name:               WWW-Vox
version:            1.2
abstract:           Interact programmatically with Vox
author:
    - Mark Paschal <mark@sixapart.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Image::Info:       1
    JSON::Any:         1
    Test::MockObject:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
